# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiniVIBE' do
  # Comment the next line if you don't want to use dynamic frameworks
pod 'SwiftLint'

  # Pods for MiniVIBE

end
